### obtener todos los materials
GET http://localhost:3006/api/materials

### obtener un material
GET http://localhost:3006/api/materials/m285

### crear un nuevo material
POST http://localhost:3006/api/materials
Content-Type: application/json

{
    "name":"Teclado",
    "description":"Mecánico con luces RGB",
    "stock":10,
    "cost": 25000
}

### modificar un material 
PUT http://localhost:3006/api/materials/m285
Content-Type: application/json

{
    "name":"Teclado Gamer",
    "stock":8
}

### borrar un material
DELETE http://localhost:3006/api/materials/idMaterial